indexer-api/src/infra/api.rs

The `health` endpoint has long been deprecated, because it is just an alias for the `ready` endpoint. For the upcoming v3 release of the Indexer we now remove it.

feat(indexer-api): remove deprecated health endpoint

---

chain-indexer/src/domain/transaction.rs
chain-indexer/src/domain/zswap.rs
chain-indexer/src/infra/node.rs
chain-indexer/src/infra/storage/postgres.rs
chain-indexer/src/infra/storage/sqlite.rs
docs/api/v1/api-documentation.md
indexer-api/graphql/schema-v1.graphql
indexer-api/src/domain/transaction.rs
indexer-api/src/infra/api/v1.rs
indexer-api/src/infra/api/v1/subscription/wallet.rs
indexer-api/src/infra/storage/postgres.rs
indexer-api/src/infra/storage/sqlite.rs
indexer-common/migrations/postgres/001_initial.sql
indexer-common/migrations/sqlite/001_initial.sql
indexer-common/src/domain.rs
indexer-tests/e2e.graphql
indexer-tests/src/e2e.rs
indexer-tests/tests/local_e2e.rs
indexer-tests/tests/storage.rs
wallet-indexer/src/infra/storage/postgres.rs
wallet-indexer/src/infra/storage/sqlite.rs

Ledger v5 introduces a richer `TransactionResult` which conveys segment results (a segment ID to success mapping) for the partial failure. This information needs to be indexed and served via the API, too. Therefore a breaking change is needed, because the transaction result is no longer a simple tag/enum-variant, but a structured object. As the change is breaking, we also rename `ApplyStage` to `TransactionResult` to no longer invent fancy names for well known ledger terms.

feat: rename ApplyStage to TransactionResult and add segment results

---

indexer-api/src/domain/storage/unshielded_utxo.rs
indexer-api/src/infra/storage/postgres/unshielded_utxo.rs
indexer-api/src/infra/storage/sqlite/unshielded_utxo.rs

Fixes #99
Fixes UTXO output ordering in GraphQL API to return UTXOs in consistent ascending order by `output_index` instead of random database insertion order.
The `unshieldedCreatedOutputs` and `unshieldedSpentOutputs` fields in GraphQL transaction queries were returning UTXOs in inconsistent order:
**Before:**
```json
"unshieldedCreatedOutputs": [
{ "outputIndex": 15, "owner": "...", "value": "5000000000000000" },
{ "outputIndex": 4, "owner": "...", "value": "5000000000000000" },
{ "outputIndex": 24, "owner": "...", "value": "5000000000000000" },
{ "outputIndex": 1, "owner": "...", "value": "5000000000000000" }
]
```
**After:**
```json
"unshieldedCreatedOutputs": [
{ "outputIndex": 1, "owner": "...", "value": "5000000000000000" },
{ "outputIndex": 4, "owner": "...", "value": …
```

fix(indexer-api): ensure consistent UTXO ordering by output_index in GraphQL API

---

indexer-api/src/infra/api.rs
indexer-api/src/infra/api/v1.rs
indexer-api/src/infra/api/v1/query.rs
indexer-api/src/infra/api/v1/subscription/unshielded.rs

Closes #135
• Enhance user experience by replacing generic "Internal Error" with clear validation messages for network mismatches
• Add extension trait `UnshieldedAddressResultExt` following team's established error handling patterns
• Return actionable error with code "NETWORK_MISMATCH" when address is from wrong network
• Apply pattern consistently across all UnshieldedAddress endpoints (queries and subscriptions)
• Follow ViewingKey validation approach suggested by @hseeberger
• Only expose network mismatch errors; other format errors remain as "Internal Error" for security
• Centralised error handling logic in extension trait for maintainability
- ✅ If I test with an unshielded address from a different environment (expected behaviour from the change here) :
- ❓If I change the network …

feat: improve error handling for network ID mismatches in unshielded address queries

---

indexer-api/src/infra/api.rs
indexer-api/src/infra/api/v1.rs

Fixes https://github.com/midnightntwrk/midnight-indexer/issues/173
Fixes an issue where block subscriptions with unknown hash return "Internal Server Error" instead of the actual error message.
When subscribing to blocks with an invalid/unknown hash, the API was returning:
- Status: 500 (Internal Server Error)
- Message: "Internal Server Error"
- Logs showed: `"block with hash ... not found"`
Updated error handling to properly distinguish between client and server errors:
- Missing blocks are now treated as client errors (400) since they're caused by invalid input
- The actual error message is returned to the client

fix: return client error for unknown block hash in subscriptions

---

indexer-api/src/infra/api/v1/transaction.rs

Fixes PM-18643 where querying the `transaction` field on any `ContractAction` (Deploy/Call/Update) caused the API to panic and forcibly close the socket connection.
The `ContractAction` GraphQL interface requires a `From<Result<Transaction<S>, ApiError>>` trait implementation for async-graphql to properly resolve the transaction field. The previous implementation had `unimplemented!()` which caused a panic whenever the transaction field was queried.
Implemented proper error handling in the `From` trait:
- Returns the transaction on success
- Panics with descriptive error message on failure (required since From trait cannot return Result)
✅ Tested with Giuseppe's exact query that was causing the issue:
```graphql
query {
contractAction(
address: …
```

fix: resolve panic when querying transaction field on ContractAction interface

---

justfile

Fixes race condition where indexer services attempt to connect to Postgres before it's fully ready.
The `run-indexer-api`, `run-chain-indexer`, and `run-wallet-indexer` recipes start Postgres and NATS containers with `docker compose up -d` and immediately try to connect. On first run, Postgres may not be ready, causing connection errors:
- `Connection reset by peer (os error 54)`
Added `--wait` flag to `docker compose up -d` commands. This makes Docker Compose wait for the Postgres healthcheck to pass before returning, ensuring the database is ready before the application attempts to connect.
- Updated `justfile` recipes to use `docker compose up -d --wait` for:
- `run-chain-indexer`
- `run-wallet-indexer`
- `run-indexer-api`
Run `just run-indexer-api` - it should connect successfully on …

fix: add --wait flag to docker compose commands to prevent race condition

---

docs/updating-node-version.md

Adds documentation to prevent incomplete node version updates.
When updating to support new node versions, multiple files must be changed in sync. Missing any of these causes indexer failures.
- Created `docs/updating-node-version.md` with:
- Complete checklist of files requiring updates
- Step-by-step instructions for metadata generation
- Common mistakes to avoid
- Testing procedures
- Rollback guidance
- Emphasises using `ripgrep` to find all occurrences (per @hseeberger's guidance)
- Lists exact files and line numbers that need updating
- Includes local testing steps to catch issues before PR

docs: add comprehensive guide for updating node versions

---

generate_txs.sh
indexer-common/src/domain/ledger/transaction.rs
justfile
wallet-indexer/src/application.rs

The logic to determine if a transaction is relevant for a (zswap) viewing key was broken: First, absence of `guaranteed_coins` was treated as `true`, but the opposite is the case. This resulted in a lot of false positives. Second, `fallible_coins` (possibly) were treated the wrong way: Instead of requiring all fallible coins to be able to be decoded it should be enough if any can be decoded.
Other changes:
- Remove some `debug` calls in wallet-indexer's code which resulted in log event tsunamis.
- Change `generate_txs.sh` to use the Dockerized toolkit (instead of a local install) which can be properly versioned.

fix: correctly determine transaction relevance

---

chain-indexer/src/infra/subxt_node.rs
chain-indexer/src/infra/subxt_node/runtimes.rs

This should fixx #317. 
It fetches the authorities which are used to determine the block author from the respective bock (hash) instead of the latest block.
Then there are some cosmetic changes wrt parameter lists.

fix(chain-indexer): fetch authorities for historic block

---

.github/workflows/build-indexer-images.yaml

Fixes the Docker Compose validation job in the GitHub Actions workflow that was failing to pull the correct node image due to incorrect node version extraction.
The workflow was trying to parse the justfile to extract the node version using grep and sed, but the justfile uses shell command substitution (`cat NODE_VERSION`) which doesn't get evaluated by the regex. This caused the workflow to try pulling an image with the literal tag `node_version := \`cat NODE_VERSION\`` instead of the actual version.
Changed the workflow to read the node version directly from the `NODE_VERSION` file, matching how it's done elsewhere in the codebase.
- Updated `.github/workflows/build-indexer-images.yaml` line 193 to use `cat NODE_VERSION` instead of parsing the justfile

fix: correct node version extraction in GitHub Actions workflow

---

.github/workflows/qa-integration-tests-base-workflow.yml
qa/tests/data/static/devnet/transactions.json
qa/tests/data/static/devnet/viewing-keys.json
qa/tests/tests/integration/basic/subscriptions/block-subscriptions.test.ts
qa/tests/tests/integration/basic/subscriptions/shielded-transaction-subscriptions.test.ts
qa/tests/tests/integration/basic/subscriptions/unshielded-transaction-subscriptions.test.ts
qa/tests/tests/smoke/graphql-healthchecks.test.ts
qa/tests/types/vitest.d.ts
qa/tests/utils/indexer/websocket-client.ts

Failures have been identified and fixed on a number of test cases. However there are tests related to Shielded Transactions that keep failing, this is because of the faucet being removed from the genesis block.
These tests will have to be properly updated when we have a way to mint custom shielded tokens

test: fixing tests failing on devnet

---

chain-indexer/src/domain/dust.rs
chain-indexer/src/domain/ledger_state.rs
chain-indexer/src/domain/transaction.rs
chain-indexer/src/infra/storage.rs
indexer-api/graphql/schema-v1.graphql
indexer-api/src/domain/storage/dust.rs
indexer-api/src/infra/api/v1/dust.rs
indexer-api/src/infra/api/v1/query.rs
indexer-api/src/infra/storage/dust.rs
indexer-common/src/domain/dust.rs
indexer-common/src/domain/ledger/ledger_state.rs
indexer-tests/e2e.graphql
indexer-tests/src/e2e.rs

Closes #353
This PR addresses confusion around DUST event types identified during code review. It cleans up the type hierarchy and aligns naming with existing patterns in the codebase (e.g., ContractAction types).
- **Remove unused registration variants**: Removed 4 registration event variants (`DustRegistration`, `DustDeregistration`, `DustMappingAdded`, `DustMappingRemoved`) from `DustEventAttributes` that were never used as DUST events - these go directly to `cnight_registrations` table
- **Align naming with existing patterns**:
- `DustEventType` → `DustEventVariant` (consistent with `ContractActionVariant`)
- `DustEventDetails` → `DustEventAttributes` (consistent with `ContractActionAttributes`)
- `ProcessedDustEvents` → `DustEventProjections` (clearer intent as event projections)
- …

refactor: clean up DUST event types and align with existing patterns

---

.github/workflows/checkmarx.yaml
.github/workflows/rust-security-scan.yaml

Updating upload-sarif-github-action to latest main branch commit which includes Checkmarx CLI v2.3.35 upgrade.
- Checkmarx support (ticket #00254934) recommended upgrading to CLI v2.3.35
- We're experiencing intermittent race condition failures (10-20% failure rate) with CLI v2.3.29
- The upload-sarif-github-action PR upgrading CLI was merged (main branch: a0cd00c4)
- Update checkmarx.yaml from `8202d218...` to `a0cd00c4...` (gets CLI v2.3.35)
- Pin rust-security-scan.yaml from `main` to `a0cd00c4...` (consistency and CLI v2.3.35)
Following Checkmarx support's suggestion to test v2.3.35, though release notes show no race condition fixes:
- Will monitor CI runs for "concurrent map read and map write" errors
- May need to re-run workflows multiple times due to intermittent nature (10-20% …

chore: update upload-sarif-github-action to a0cd00c4

---

.github/workflows/ci-cloud.yaml
.github/workflows/ci-standalone.yaml
justfile
rust-toolchain.toml

Rust 1.90 includes a new default faster linker on linux: https://blog.rust-lang.org/2025/09/18/Rust-1.90.0/

chore(deps): bump Rust to 1.90.0

---

chain-indexer/src/application.rs

Fixes #367
Removes an incorrect assertion that was causing panics when two independent subscription streams were temporarily out of order. This is normal async behavior, not a bug.
Simon Gellis reported assertion failures on EC2 instances (issue #367). His analysis was correct: the assertion incorrectly enforced ordering between two independent WebSocket subscriptions that have no ordering guarantee.
The code had two independent async tasks:
1. `highest_block_on_node_task` - subscribes to highest finalized blocks
2. `index_blocks_task` - processes blocks
The assertion `assert!(node_block_height >= block.height)` incorrectly assumed the first stream would always be ahead. This is false - they're independent subscriptions with no synchronization.
```diff
- assert!(node_block_height >= …
```

fix: remove incorrect assertion on stream ordering in chain-indexer

---

.github/workflows/rust-security-scan.yaml

Adds SARIF output format to cargo-deny security scanning, enabling upload to Checkmarx for unified security reporting.
cargo-deny 0.18.5 (released Sep 22, 2025) now supports SARIF output via PR [EmbarkStudios/cargo-deny#790](https://github.com/EmbarkStudios/cargo-deny/pull/790). This enhancement allows us to capture and upload cargo-deny findings to Checkmarx alongside our existing cargo-audit results.
- Modified `.github/workflows/rust-security-scan.yaml`:
- Added `-f sarif` flag to cargo-deny to generate SARIF output
- Added step to upload `cargo-deny.sarif` to Checkmarx
- Renamed existing upload step for clarity (cargo-audit SARIF)
cargo-deny provides more comprehensive security scanning than cargo-audit alone:
- **Security vulnerabilities** (same as cargo-audit)
- **License compliance …

ci: add cargo-deny SARIF output to security scanning

---

indexer-api/graphql/schema-v1.graphql
indexer-api/src/infra/api/v1/block.rs

The original PR : #382
As suggested by Simon in PM-19761, 'ledgerParameters' is more explicit than the generic 'parameters' field name. This makes it clear that these are specifically the ledger's parameters, not block parameters or something else.
Jira ticket comment : https://shielded.atlassian.net/browse/PM-19761?focusedCommentId=37230

refactor: Rename GraphQL field from parameters to ledgerParameters

---

chain-indexer/src/infra/storage.rs
indexer-api/graphql/schema-v1.graphql
indexer-api/src/domain/unshielded.rs
indexer-api/src/infra/api/v1/unshielded.rs
indexer-api/src/infra/storage/unshielded.rs
indexer-common/migrations/postgres/001_initial.sql
indexer-common/migrations/sqlite/001_initial.sql
indexer-common/src/domain.rs
indexer-common/src/domain/ledger/ledger_state.rs
indexer-common/src/infra/sqlx.rs

Adds DUST generation registration tracking to the `UnshieldedUtxo` type by introducing two new fields: `initial_nonce` and `is_registered_for_dust_generation`. This enables the wallet to track which Night tokens have been registered for DUST generation.
The wallet needs to identify which unshielded UTXOs are registered for DUST generation. This requires:
1. Computing the `initial_nonce` for each UTXO using the formula: `InitialNonce(persistent_commit(&output_index, intent_hash))`
2. Checking registration status against `LedgerState.dust.generation.night_indices`
This implementation became possible with ledger-6.1.0-alpha.3, which made the required cryptographic functions publicly accessible (via Jegor's wallet PR 50).
**Domain Layer** (`indexer-common`):
- Added semantic type alias …

feat: add DUST registration tracking to UnshieldedUtxo

---

.github/renovate.json5

Otherwise renovate will attempt to detect semantic commits, this forces it to do so all the time.
Also shows open scorecard of updated dependencies in PRs (information only change).

chore(build): renovate use semantic commits

---

indexer-common/src/domain/ledger/ledger_state.rs

The indexer is "making up" an intent hash for UTXOs created by ClaimRewards transactions. The ledger has its own process for computing this intent hash, which is different from the indexer. This means that the indexer has a different list of UTXOs than the ledger (and therefore the node), making it impossible to build a valid transaction using just the indexer's API.
Update the indexer to use the same intent hashes as the ledger. For reference, the ledger's logic can be found at https://github.com/midnightntwrk/midnight-ledger/blob/815ba76f7a38d85c290bb93e152a5feca35022fd/ledger/src/semantics.rs#L1438-L1444.

fix: use same intent hash for ClaimRewards as ledger

---

indexer-common/src/domain/ledger/ledger_state.rs

We were using the wrong intent hash when fetching spent UTXOs. Specifically we were using the hash of the intent where they were spent, rather than the hash of the intent where they were created.
This meant the indexer never considered existing UTXOs to be spent, and considered new UTXOs to be immediately spent in the TX where they were created.

fix: use correct intent hash for spent UTXOs

---

indexer-common/src/domain/ledger/ledger_state.rs

Closes : [PM-19840](https://shielded.atlassian.net/browse/PM-19840)
The indexer was incorrectly creating UTXOs for transactions with `TransactionResult::Failure`. These UTXOs don't exist on the ledger since failed transactions make no state changes.
- When a transaction completely fails (`TransactionResult::Failure`), the ledger returns unchanged state
- The indexer was still processing segment 0 and creating UTXOs for these failed transactions
- This caused the indexer state to diverge from the actual ledger state
- Users would see phantom UTXOs that don't actually exist
Added an early return in `make_unshielded_utxos_v6` to skip UTXO creation entirely when `TransactionResult::Failure` is encountered.
- Discovered by @simongellis when investigating invalid transactions on devnet
- Thomas …

fix: skip UTXO creation for failed transactions

---

.github/workflows/qa-integration-tests-base-workflow.yml
.github/workflows/qa-integration-tests-devnet.yml
.github/workflows/qa-integration-tests-undeployed.yml
qa/tests/tests/e2e/shielded-transactions.test.ts
qa/tests/tests/e2e/unshielded-transactions.test.ts
qa/tests/tests/integration/basic/queries/block-queries.test.ts
qa/tests/tests/integration/basic/subscriptions/unshielded-transaction-subscriptions.test.ts
qa/tests/upload-to-xray.sh
qa/tests/utils/reporters/custom-xray-json/README.md
qa/tests/utils/reporters/custom-xray-json/xray-json-reporter.ts
qa/tests/utils/reporters/index.ts
qa/tests/vitest.config.ts

This change enables the test results (generated with an additional custom 
reporter that uses XRay JSON format) to be uploaded to XRay
It adds:
- A README with instructions on how it can be used
- Custom reporter that uses XRay JSON format
- Changes to Vitest configuration file
- A script to upload the test report
- An example on what to do on the test cases

test: added support to upload test results in XRay
